---
- name: Update apt cache (Debian/Ubuntu)
  ansible.builtin.apt:
    update_cache: true
  when: ansible_pkg_mgr == 'apt'
  tags: install

- name: Install rsyslog (Debian/Ubuntu)
  ansible.builtin.apt:
    name: rsyslog
    state: present
  when: ansible_pkg_mgr == 'apt'
  tags: install

- name: Install rsyslog (RHEL/CentOS/Fedora)
  ansible.builtin.dnf:
    name: rsyslog
    state: present
  when: ansible_pkg_mgr == 'yum'
  tags: install

- name: Install rsyslog (Alpine)
  community.general.apk:
    name: rsyslog
    state: present
  when: ansible_pkg_mgr == 'apk'
  tags: install

- name: Install rsyslog (Arch Linux)
  community.general.pacman:
    name: rsyslog
    state: present
  when: ansible_pkg_mgr == 'pacman'
  tags: install

- name: Configure log forwarding to Graylog
  ansible.builtin.lineinfile:
    dest: /etc/rsyslog.conf
    line: '*.* action(type="omfwd" target="{{ syslog_server }}" port="{{ syslog_port }}" protocol="udp" action.resumeRetryCount="100" queue.type="linkedList" queue.size="10000")'
    insertafter: EOF
  notify: Restart rsyslog
  tags: configure

- name: Validate rsyslog configuration
  ansible.builtin.command: "rsyslogd -N1"
  changed_when: false
  register: rsyslog_validation
  failed_when: rsyslog_validation.rc != 0
  tags: configure
